openapi: 3.0.0
info:
  title: Recommendation Service
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /recommendations/{user_id}:
    get:
      summary: Get product recommendations for a user
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of product recommendations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recommendation'
components:
  schemas:
    Recommendation:
      type: object
      properties:
        product_id:
          type: string
        recommendation_score:
          type: number
